name: Eslint test

on: 
  pull_request:
    branches: 
    - master

jobs:
  eslint:
    name: eslinter
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v1
      
    - name: ESLint Action
      uses: hallee/eslint-action@1.0.1
